localPath = scriptPath()
imagePath = (localPath .. "luar/1farmImage/")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/packx.png", imagePath .."packx.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/topupgoldx.png", imagePath .."topupgoldx.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/eventcenterx.png", imagePath .."eventcenterx.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/shipmentcoll.png", imagePath .."shipmentcoll.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/shipmentcollx.png", imagePath .."shipmentcollx.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/helpfriends.png", imagePath .."helpfriends.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerhelp.png", imagePath .."towerhelp.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerhelp1.png", imagePath .."towerhelp1.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerhelp2.png", imagePath .."towerhelp2.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towercon.png", imagePath .."towercon.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerenter.png", imagePath .."towerenter.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerenteryes.png", imagePath .."towerenteryes.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerlvl2.png", imagePath .."towerlvl2.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerlvl2yes.png", imagePath .."towerlvl2yes.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerlvl2gat.png", imagePath .."towerlvl2gat.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerlvl2gatop.png", imagePath .."towerlvl2gatop.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerlvl2march.png", imagePath .."towerlvl2march.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/shipmentcoll.png", imagePath .."towerlvl2set.png")
httpDownload("https://raw.githubusercontent.com/autozfarmz/auto1200x1920/master/luar/1farmImage/towerlvl2stepout.png", imagePath .."towerlvl2stepout.png")
scriptExit("You have Updated the auto zFarmz image library!")
